### PR TITLE
fix core.Ion.gofnt when computed against Ne

### PR DESCRIPTION
**Pull request by ghost**
`core.Ion.gofnt` throws `ValueError: Input object to FillWithScalar is not a scalar` when called with fixed temperature. However, it works fine when called with fixed density. 

This PR fixes the bug at fixed temperatures by copying the code used for fixed density.

### CODE REVIEW

**Review by kdere — COMMENTED** [review]
I am surprised that this is happening.  It used to be that the temperature and densities were set to arrays of the same size, even if one had all of the same values.

**Comment by kdere** [comment]
I would like to let @wtbarnes take a look at this before merging as it looks iike his code that is being fixed.

**Comment by kdere** [comment]
also, thanks for your input

**Comment by ghost** [comment]
Sure, it’s worth checking that it does not break other things! 

Here’s the code I use to produce the error:

~~~python
import ChiantiPy.core as ch
import numpy as np

Ne = np.logspace(6, 12, 100)
Te = 1e6

ion = ch.ion('fe_12', temperature=Te, eDensity=Ne)
ion.gofnt(wvlRange=[195.11, 195.12])
~~~

While using `Ne = 1e9` and `Te = np.logspace(5, 7, 100)` works just fine.

**Comment by kdere** [comment]
your code looks pretty straightforward and should work.

**Comment by kdere** [comment]
seems to work now

**Comment by wtbarnes** [comment]
@gpelouze Thanks for your contribution.

@kdere I do not think I've made any modifications to the G(n,T) function. 

We seem to have these sorts of problems arise quite a bit because we handle T and n of different sizes (and different combinations thereof) as different cases. I think this can largely be avoided with the broadcasting features in NumPy.

**Comment by kdere** [comment]
for the Ion.Ion class, I make Temperature and EDensity the same size.  Both are either floats or 1D numpy arrays of the same size.  This is helpful when I got to the populate method and save me from editing a lot of code whenever there is a change in population processes

**Comment by wtbarnes** [comment]
I guess my point is that there should be one place where the differences in dimensionality are reconciled (maybe in `__init__`), i.e. converting floats to arrays of len 1, and then after that, the code should be agnostic to the sizes of the n,T arrays. Currently, I think there is some redundancy in the checking of various n, T dimensions

**Pull request merged**
