### PR TITLE
a number of changes to ion.setup, ion.populate io.elvlcWrite

### PR DESCRIPTION
**Pull request by kdere**
ion.setup() now looks for an .auto files containing autoionization rates as this is where CHIANTI is moving in the near future
ion.populate() now understands the use of the autoionization values, if present
ion.populateNew() is added for development work
manifest.in now includes README.txt

### CODE REVIEW

**Comment by wtbarnes** [comment]
Regarding merging unfinished functions/objects into master with the `New` prefix, I don't think this is in general a good idea. I think the better solution to this is to have these parts of the code that are in development on a new branch of your fork of ChiantiPy.

You can then create a PR/multiple PRs from these branches to show that these are being worked on. They need not be merged until the work is complete on them.

That way, there is not duplicate or semi-functional code on the master branch.

**Comment by kdere** [comment]
That is probably a good idea.  Just need to figure out how to do it.  I am sure there are directions somewhere

**Comment by wtbarnes** [comment]
Probably the best way to do this is just to make copies of those files affected (the ones with the `New` modules or functions) and put them somewhere outside the repo (e.g. your desktop). Then delete them from the repo and push and merge. All this would be on the master branch.

Then, go in and create a new branch (something like `ion-dev` or `populate-dev`) and switch to it. 
```shell
$ git branch ion-dev
$ git checkout ion-dev
```
and then paste back in the development bits of code that you pulled out previously. Then, push this branch up to your fork and create a pull request against master. Maybe best to have multiple branches/PRs for the `IonNew.py`, `ion.populateNew()`, etc.

**Comment by kdere** [comment]
In the past I have tried using branches with svn but found that the branches became stale after a while - there was a lot of code updated in the trunk.  But it looks like with git I can just merge the newly developed piece of code.  Will give a try.

**Comment by kdere** [comment]
is it easier to create a branch through Github?

**Comment by kdere** [comment]
what I would like to know is what my directory structure will look like.  I have an IDE the I like (Eric) that pulls in everything under a certain directory.  Will a branch have a parallel structure but different top level directory?

**Comment by wtbarnes** [comment]
You can create branches either at the command line or on GitHub. Ideally, the branches on your remote and local are the same though they don't have to be. For the sake of simplicity, I would recommend just creating 

Creating/deleting branches will have no impact on your directory tree or choice of IDE/editor. When you create a new branch, you are splitting (or "branching") off from the main line of development, usually the master branch. All of the differences are managed internally by git so you don't need to manage multiple copies of the code in different directories. [Some more info on branching in git here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging).

So as an example with the new additions to the populate method you're working on, starting on the master branch, you would first create a new branch (call it "pop_improvements" or whatever you want) and switch to it,
```shell
$ git branch pop_improvements
$ git checkout pop_improvements
```
Now, make any changes related to the improvements in the populate method, add them and commit them. If you want to push up this new branch to github,
```
$ git push origin pop_improvements
```
and then the new branch will show up on your fork of ChiantiPy. Then you can create a PR from this branch against the main repo.

You can switch back to the master branch anytime,
```
$ git checkout master
```
So you essentially have multiple snapshots of your codebase, but this is all managed by git. In this way, you can continue to work on larger features (e.g. the new additions to `populate`) on different branches, while still making bug fixes or smaller additions on the master branch.

**Comment by wtbarnes** [comment]
One additional note: I've not used SVN or other older version control systems, but my understanding is that the way these versioning systems managed things like branches is very different than the way git does things. So comparing git branches with SVN branches might be making things more confusing.

**Comment by kdere** [comment]
well, i did a 
> git branch pop-dev
> git checkout pop-dev
I think I understand what is happening.  The directory layout remains the same but I am in a different branch although you can not tell just by doing an 'ls' on the directory

**Comment by wtbarnes** [comment]
Exactly. I've found it helpful to modify your .bashrc (or bash_profile or whatever) such that the name of the branch shows up on the command line when you are inside a repo in the terminal. That way, you always know what branch you're on.

Similarly, many editors/IDEs also have git extensions that will list what branch you are on. I would imagine Eric has a plugin for git.

**Pull request merged**
