### PR TITLE
Add test of radloss and spectrum-like classes array and scalar input combinations

### PR DESCRIPTION
**Pull request by svaberg**
Added some tests of the spectrum, bunch, mspectrum, ipymspactrum and radloss classes' ability to handle scalar and array inputs based on my understanding of how the classes are meant to work and what arguments they are meant to accept for temperature, density, and/or emission measure. 

The tests that fail all seem to fail for a small number of reasons and if these are fixed all the tests would succeed!

### CODE REVIEW

**Comment by kdere** [comment]
it looks to me like this test should probably belong under core/tests where the currently has a test_spectrum.  One of the things that ChiantiPy has been missing is checking on the temperature, density and emission measure variables and it looks like you are doing that here so that is good.  But if it could be under ChiantiPy/core/tests it would fit in with the way that I currently run pytest (locally)

**Comment by svaberg** [comment]
Hi Ken,

Thanks for this! I can move it into `ChiantiPy/core/tests` and update this pull request. As the test only tests classes in the `core` folder this seems like the test's rightful home.

Generally, as long as you run PyTest locally from the Chianti root folder it will recursively pick up tests in the project, including the ones in `ChiantiPy/ChiantiPy/tests`.

**Comment by svaberg** [comment]
The tests I wrote are now in the file `ChiantiPy/ChiantiPy/core/tests/test_spectrum_api.py`.

**Comment by kdere** [comment]
I committed your tests and ran them.  There were a number of failures but a number of them looked familiar to me so I will check them out.

**Comment by svaberg** [comment]
Cool! The tests are based on my understanding of the AP. If any of the tests abuse the API feel free to delete as many as needed of course.

**Pull request merged**
