### PR TITLE
Continuum refactor

### PR DESCRIPTION
**Pull request by wtbarnes**
This PR is a **work in progress and is not yet ready to be merged.**

Refactor the `continuum` class.  Currently, the output of the continuum class does not match that of the CHIANTI IDL code. For more info on this, see #108. This PR fixes the free-free and free-bound continuum emission methods and generally cleans up the continuum module.

A couple of changes this PR would ideally incorporate:
* One method for free-free and and one for free-bound
* Keyword arguments to include/not include abundance and ionization equilibrium
* Free-free and free-bound methods should directly return the result rather than setting a FreeFree/FreeBound dictionary. These methods are relatively fast so storing the result isn't really necessary.
* Raise exceptions rather than returning an 'errorMessage' in dictionary or just printing to the screen and returning

@kdere what do you think of the above proposed changes? They break a bit from the conventions used in ChiantiPy thus far, but I think would help to improve readability and be a bit more concise.

**NOTE:** If implemented, other parts of ChiantiPy that use the continuum module will need to be adjusted (as well as the continuum tests), but this is a relatively small undertaking.

### CODE REVIEW

**Comment by kdere** [comment]
The 'collision' number is widely seen in papers on excitation etc but it is generally not shown where it comes from.  That is what the constants module does.  I would prefer to leave it there.  As it shows up in many methods, it is then possible to see the resemblance.
I like the idea that the continuum modules provide a dict to the main object.  I would rather see a keyword the says to also return a dict.

**Comment by wtbarnes** [comment]
I have not removed the `collision` constant from the constants module. The only constants I've removed are those explicitly related to the free-free calculation (`freeFree`, `sutherland`, and `freeFreeLoss`) and the free-bound calculation. They are now defined locally within their respective  methods since they are not used anywhere else (as far as I can tell) in the package.

**Comment by wtbarnes** [comment]
I can understand setting an attribute for intermediate results that are used in other methods in order to avoid doing expensive things twice (as is the case in the ion class). However, what is the advantage of doing that here? The free-free and free-bound methods are not used by each other and also are not very intensive so there does not seem to be any benefit to "cacheing" a result in an attribute. If another object depends on the continuum emission in several places, than that object should set its own attribute.

My main reason for letting the free-free/free-bound methods return values rather than setting attributes was that is more explicit what the method is doing when a value is returned. When an attribute is set, it is less clear to the user what has happened after they've made that method call and requires extra explanation in the documentation. 

If the free-free/free-bound methods were to set attributes rather than returning values, why does the attribute need to be a dictionary? I think just the value of the emission (whether free-free or free-bound) should be sufficient.

**Comment by wtbarnes** [comment]
## TODO List
A few things to do before this PR can be merged. For my benefit.
- [ ] Fix continuum tests
- [ ] Fix other modules which use continuum module
- [ ] Documentation

**Comment by kdere** [comment]
First, I think it is early in things to change the basic way that the ion class works.  This class is used by just about everything else.  In particular, with the multiprocessing and ipyparalel modules.  I do not really understand what is happening there.  So, for one thing, I use then return a dict with 'errorMessage' to indicate when things are retrieved from the cores, I have an idea of whether thing worked.  It is usual to throw an exception but that nature of the exception needs to be clear when returned from one of the cores.
Also, I like the idea that all of the classes return the results as a dict that is an attirbute of the object.  Then you have all the information about how things were calculated, such as elemental abundance etc.  So, I would like to skip these kind of changes, at least, for the time being.  For me, it is not a question of calculation time.

**Comment by wtbarnes** [comment]
Just as a note,  you can do line-by-line code review on pull requests in GitHub by clicking on the "Files changed" tab and then clicking on the blue plus sign that pops up by the line number. That way, your comments are attached to specific portions of the code.

EDIT: OK I see that you've commented on my individual commits. For some annoying reason, GitHub just shows these as one whole stream in the "Conversation" tab. The line-by-line comments might be more useful.

**Comment by wtbarnes** [comment]
Regarding your first comment about changes to how these values are returned, i.e. as dicts and attributes or just as values:

Just to be clear, I have not modified the `ion` module at all. This PR is limited to the continuum module with some minor changes to the `data` and `constants` module. I agree that making changes to the `ion` class is complicated because it touches nearly every other part of the package.

Regarding attributes versus return values, I think a good option would be to let the free-free and free-bound methods both return a value and set the value of the emission as an attribute so that it can still be easily referenced later, whether that is just an array or a dictionary. So this might look like:

```Python
class Continuum(object):
    def free_free(self,wavelength):
        # do a bunch of stuff
        self.free_free_emiss = free_free_emiss
        return self.free_free_emiss
```

Regarding exception handling versus returning 'errorMessage' approach, I think the biggest issue here is that the 'error_message' in a dictionary approach does not immediately tell the user what the problem is and in the worst case scenario they might not realize there is a problem at all. If an exception is raised, there's no way to avoid seeing that you've done something wrong. Additionally, exceptions can still be caught when using multithreading. So all that would be needed is a `try...except` in the place of `if 'errorMessage' in dictionary:...`.

Looking at the package, I see four different modules (outside of the `Continuum` module itself and the tests) where `continuum` is used:
* `tools/mputil`
* `core/radLoss`
* `core/spectrum`
* `core/ipymspectrum`

I believe each one calls the `continuum` module a maximum of 4 times. Adding try-except here is a pretty small task.

I understand wanting to preserve all of the information that went into the calculation (abundance, ionization equilibrium, etc.,), but isn't this information already contained in the `continuum` object itself? The object is essentially already a dictionary with all of this info. If there are cases in the multiprocessing module where all of this info needs to be sent back from the child process to the parent process, why not let the multiprocessing code do this packaging?

**Comment by kdere** [comment]
the problem I see in returning values is that when I typically use ChiantiPy I am not expecting a return so that if I kept using it in the usual way, I would suddenly get a lot of print out in my ipyhton/.jupyter session.  I would like to make that optional with a keyword such as 'return_result' or something like that.  I would prefer that the default value would be not to return the result.  Or, to put that in the defaults file.

**Comment by kdere** [comment]
with regard to checking for exceptions instead of producing a dict with 'errorMessage', how would this work?  If a calculation returns from a core or something and has an error, how would you know that an error had occurred.

**Comment by wtbarnes** [comment]
I think because of the way you've constructed the `mspectrum` module with `mputil`, this is relatively easy. Take for example the [multiprocessing helper for the free-bound calculation](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/tools/mputil.py#L30). Let's assume that the method `free_bound` sets an attribute `free_bound_emission`, a 2D Numpy array, and a `ValueError` is raised if there is no free-bound information available about this ion in CHIANTI. 

```Python
def doFbQ(inQ, outQ):
    for inputs in iter(inQ.get, 'STOP'):
        ionS = inputs[0]
        temperature = inputs[1]
        wavelength = inputs[2]
        abund = inputs[3]
        em = inputs[4]
        fb = ChiantiPy.core.Continuum(ionS, temperature, abundance=abund, em=em)
        try:
            fb.free_bound(wavelength)
            outQ.put(fb.FreeBound)
        except ValueError:
            outQ.put(np.zeros((len(temperature),len(wavelength)))
```
You can optionally add a print or logging statement in the exception block to let the user know an ion has been skipped.

Then, in the [`mpspectrum` module](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Mspectrum.py#L196) where this is returned, nothing needs to be checked because it is just set to zero if a value was not available,

```Python
for _ in range(fbWorkerQSize):
    thisFreeBound = fbDoneQ.get()
    freeBound += thisFreeBound
```

So I don't really think the child process needs to even let the parent know about the 'error message' or exception or whatever. It just has to handle it appropriately and be able to return a sensible result.

**Comment by wtbarnes** [comment]
Regarding the setting an attribute versus returning a value, I would rather avoid another keyword and if statement that would be needed to choose whether to return the value or not. So I think it would be best in this case to just stick to setting an attribute, here `free_free_emission` and `free_bound_emission`.

In general though, I think it is better practice (especially in Python, where there aren't really public and private variables) to return a value from functions like these, where some output is being calculated from some input. Setting a dictionary and not returning anything (or returning `None`) just makes it less clear to the user what happened when they made that function call versus if they get a result back printed to the screen, they know something has happened.

**Comment by kdere** [comment]
I could not tell if you had changed the method for interpolating the sutherland gaunt factors.  It looks like you dropped the matplotlib triangulation method and substituted the scipy.ndimage map_coordates.  Have you done something similar for the Itoh gaunt factors?
also, which is [skip ci]?

**Comment by kdere** [comment]
regarding catching a valueError in mputil, it is still necessary to know if something bad has happened.  Setting the results to just zero does not give this.  I would still like to return a dict with an 'errorMessage' key or something iike that

**Comment by wtbarnes** [comment]
Yes I switched to `scipy.ndimage.map_coordinates` because I've used in the past and it is simple. It's also essentially the same function as is used in the IDL implementation so it made comparing the two codes easier. 

In the Itoh method, there's no need to interpolate. See Eq. 4 of the Itoh paper. It is really just a matter of reading in the coefficients and multiplying them by the scaled temperature and density.

**Comment by kdere** [comment]
I guess I should have read the paper more carefully!

**Comment by wtbarnes** [comment]
putting [skip ci] in the commit messages tells Travis CI not to run a job for that commit. I been using it for all of these commits because I know all of the tests are going to fail until I've fixed the calls to `Continuum` in the other modules.

Could you actually revert the merge for this PR? I'd still like to clean up a few things and fix up the documentation.

**Comment by wtbarnes** [comment]
Nevermind. I will just create a new PR later to fix up the documentation and correct the RadLoss and spectrum methods and tests. However, until then, Travis will fail but that is fine.

**Comment by kdere** [comment]
sounds good.

**Pull request merged**
