### PR TITLE
Update database to v8.0.6 for tests

### PR DESCRIPTION
**Pull request by wtbarnes**
Pull down latest version of database when running tests. Maybe this will also solve transient CI failures because the database cannot be downloaded?

### CODE REVIEW

**Comment by wtbarnes** [comment]
Looks like this fixes it. Perhaps the v8.0.2 database is no longer available?

**Comment by kdere** [comment]
yes, it is now 8.0.6.  Forgot to tell you

**Comment by wtbarnes** [comment]
Good to update this anyway, but I'm not sure why the tests were failing as it seems that [the tar file for 8.0.2 is still in the same location](http://www.chiantidatabase.org/download/)

**Comment by kdere** [comment]
actually, we don't bother deleting the files just move the web link to a new file.
there is also another way to get specific files.  for example
`wget chiantidatabase.org/sswidl/dbase/ioneq/chianti.ioneq`
and so on.  That is how we distribute to SSWIDL

**Pull request merged**
