### PR TITLE
Clean up the initialisation code by removing unused parts

### PR DESCRIPTION
**Pull request by Cadair**
I think this will all work as you don't use the astropy config system you don't need the setup for it, and I have put the astropy import in a try statement so you can still import the package without astropy installed.

### CODE REVIEW

**Comment by Cadair** [comment]
for the record I have proposed this change to the package template: astropy/package-template#211

**Comment by wtbarnes** [comment]
Looks good to me. This just moves the "guts" of _astropy_init.py to the ~~setup.py~~ \_\_init\_\_.py correct?

**Comment by Cadair** [comment]
it moves it into the `__init__.py` as there didn't seem to be a lot of point keeping both files for just a few lines.

**Comment by kdere** [comment]
OK, here we go

**Pull request merged**
