### PR TITLE
 uses astropy helpers with the local static_version file

### PR DESCRIPTION
**Pull request by kdere**

### CODE REVIEW

**Comment by wtbarnes** [comment]
I think the `__init__.py` in the top level directory (seems to have been added in #159 ?) is not needed. There are no imports being done at this level.

The coverage "failure" is not really that important. Just small fluctuations in the test coverage. I think the important thing is that all of the Travis jobs are passing.

**Comment by wtbarnes** [comment]
Also the `ChiantiPy/version.py` file has not been removed.

**Comment by kdere** [comment]
Would __init__.py be needed by Python 2.7.  The setup.py file is in that directory

**Comment by wtbarnes** [comment]
I don't think so since there are no imports being done at this level.

**Pull request merged**
