### PR TITLE
Fix continuum ioneq off-by-one error and temperature dimension mismatches

### PR DESCRIPTION
**Pull request by wtbarnes**
Ioneq method was accidentally selecting an ionization state one higher.

### CODE REVIEW

**Comment by kdere** [comment]
for the free-bound calculations, it should select the ioneq of the target ion.  For example, for the FB of fe_25, the target ion is fe_26.

**Comment by wtbarnes** [comment]
Ah that's right. Ok I was thinking there was a bug in my original code. Is this also the case for free-free?

**Comment by kdere** [comment]
for free-free, the target and product are the same so you want the ioneq of fe_25 for calculating the fe_25 FF

**Comment by wtbarnes** [comment]
Ok. Let me make some minor adjustments here then...

**Comment by wtbarnes** [comment]
Ok the ioneq_one() method now takes a parameter `stage` and is called with `self.stage+1` for the free-bound emission and `self.stage` for the free-free emission.

Additionally, I've also fixed the problem with scalar temperatures related to #155 by making sure that scalar temperatures are converted to arrays of length 1. Previously they were arrays of length 0 which was what was causing the `IndexError`.

I've also added a few additional tests for the continuum module to hopefully prevent something like this from happening again.

**Comment by wtbarnes** [comment]
@kdere I've added a step in the Travis build that removes the git-tracked version.py before doing the install otherwise the tests will not pass. This is because the install step looks for attributes in the version.py file 

This lets you track the version.py like you want, but also allows the tests to pass with the auto-generated version. However, this suggest to me that running a `setup.py install` on a fresh clone will probably fail with this same error.

If you expect to move away from the astropy-helpers package in the future, then this is a bit of a moot point anyway.

**Comment by kdere** [comment]
I will probably stay with the astropy-helpers package but I just wanted to be able use Chianti either by installing it or by putting it in your path.
When someone is doing development and changing the code where does the code reside, in the site-pakcages?
Otherwise you would have to do an install after each edit.  Or, am I missing something?

**Comment by wtbarnes** [comment]
I think you're correct in needing to do an install after each edit. 

The problem is right now with the tracked `version.py`, the standard install method is broken unless you delete the `version.py` file. See my latest comment on #136. I think this might be a viable solution.

**Comment by wtbarnes** [comment]
Other than that, I think this PR is ready to be merged if you're happy with the changes.

**Comment by kdere** [comment]
I have been looking at the free-bound calculations again.  I was wrong about the ion to chose.  For fe_25, the target ion is fe_25 and the recombining ion is fe_24.  For fe_27, the completely stripped ion, fe_27 is the target ion and it is necessary to use the ioneq for fe_27 for it.  I can fix that but I can't do it right now.

**Comment by wtbarnes** [comment]
I'm a bit confused by the terminology here I think. In [Peter Young's technical report on free-bound emission](http://pyoung.org/chianti/freebound.pdf), he defines following terms:

* *recombining*: z+1, the ion prior to recombination
* *recombined*: z, the ion after recombining

The free-bound emission is then expressed as a function of the *recombining* ion number density which can be rewritten in terms of the abundance, electron density, and ionization equilibrium for the *recombining* ion. 

This seems to boil down to whether you are referencing the  recombining or recombined ion when you say "I want to calculate the free-bound emission for ion {element}_{stage}." Which ion does {stage} refer to?

 Looking at [freebound.pro in CHIANTI IDL](http://www.chiantidatabase.org/idl/continuum/freebound.pro), it seems that the ionization equilibrium is calculated for the z+1 ion.  So here, it seems that calling,

```IDL
freebound,temp,wvl,iz=26,ion=25
```

calculates the free-bound continuum emission where Fe XXVI is the recombining ion, Fe XXV is the recombined ion, and the ionization equilibrium is calculated for Fe XXVI

**Comment by kdere** [comment]
ChiantiPy does it differently

**Pull request merged**
