### PR TITLE
 added Ip in eV as attribute

### PR DESCRIPTION
**Pull request by kdere**
also changed self.temperature to self.Temperature
added old karzas latter routine for checking

### CODE REVIEW

**Comment by wtbarnes** [comment]
Could you fix the `Continuum` tests with these updated attribute names?

**Comment by kdere** [comment]
OK, will look into that

**Comment by wtbarnes** [comment]
Just a matter of changing `temperature` to `Temperature` in [this one test function](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/tests/test_Continuum.py#L24)

**Comment by kdere** [comment]
OK, think I have done that.  Was not aware of where the tests were

**Comment by wtbarnes** [comment]
Just FYI, you can put a `tests/` directory in any submodule (e.g. `core`,`tools`) and any files inside of there named as `test_{whatever}.py` will get picked up and run as tests when you run `python setup.py test` at the command line. Right now, the tests are grouped by object, but you could organize them however you want.

**Comment by kdere** [comment]
thanks for the info

**Pull request merged**
