### PR TITLE
 removed a meaningless directory

### PR DESCRIPTION
**Pull request by kdere**

### CODE REVIEW

**Comment by kdere** [comment]
somehow a meaningless directory slipped in.  just getting rid of it

**Comment by ehsteve** [comment]
@kdere just to be clear you have deleted this from the repo but all of these files still exist in the git history therefore anyone that grabs this repo through a git clone (which comes with the entire git history) will be downloading all of these extra files. They just won't be visible.

**Comment by kdere** [comment]
any way to clean out the git history?

**Comment by ehsteve** [comment]
You can edit the git history but this is a little annoying. Since it is so early on I would recommend just start over on your local computer and then push to github and overwrite the git history.

**Comment by kdere** [comment]
OK, will proceed in that direction

**Pull request merged**
