### PR TITLE
wvlRange keyword not accepted in ion.Intensity function

### PR DESCRIPTION
**Pull request by ktritz**
Couldn't get the ipymspectrum example to work in the docs.

### CODE REVIEW

**Comment by kdere** [comment]
I removed the wvlRange keyword from the ion.intensity method as it complicated matters.  It is still available in methods like ion.intensityList(), ion.intensityRatio()

I need to fix the docs to show this.  If I can't get them to build on RTD, I will build them an mount them on chiantidatabase.org somewhere

**Comment by kdere** [comment]
the docs are still not bulding on RTD.  It does find PyQt5 but not 4.  It is using Python 3.5 and I wonder if it should be pushed up to 3.6, to perhaps include the changes in the PyQt packages.  I have recently upgraded to 3.6.5 myself

**Comment by ktritz** [comment]
The wavelength keyword was still being used in the ipymspectrum code, so I just removed it and it seemed to work once I turned off the continuum calculation. There is a problem with the ipymspectrum continuum calculation which I haven't tracked down yet.

  File "C:\Users\ktritz\Anaconda3\lib\site-packages\chiantipy-0.7.dev0-py3.6.egg\ChiantiPy\core\IpyMspectrum.py", line 217, in __init__
    freeFree += thisFf

TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

**Comment by ktritz** [comment]
I'm working with Python 3.6.5

**Comment by kdere** [comment]
ipymspectrum is a bit screwed up right now.  I am going to have to straighten it out.  I moved the continuum methods back to the previous naming conventions but forgot to implement this in ipymspectrum.  May be a similar problem with spectrum and mspectrum but I will have to check this.

**Pull request closed without merging**
