### PR TITLE
Fixing broken Ion class (that I broke...)

### PR DESCRIPTION
**Pull request by wtbarnes**
PR #51 broke Ion class because of some checks on the temperature/density that I made. This corrects those. Everything works as expected now.

Need to write some tests so that this does not happen again...

### CODE REVIEW

**Comment by wtbarnes** [comment]
Hmm strange... looking into this now...

**Comment by wtbarnes** [comment]
The problem I pointed out in this PR seems to be resolved on my end. What specifically do you mean by not working?  

Re: the `abundanceName` keyword, I condensed `abundance` and `abundanceName` into a single keyword (`abundance`) such that if one supplies a float value to `abundance`, the abundance will be set to that value. If one supplies a string that is a valid CHIANTI .ab filename, the abundance is read from that file and the `AbundanceName` attribute is set accordingly.

**Comment by kdere** [comment]
I have update my local repository and now see that.  The problem is the Spectrum.bunch and Spectrum.spectrum, and probably MSpectrum and IpyMspectrum, use the abundanceName keyword and call Ion.ion with it.  I would rather leave this for you to sort out.  Thanks

**Comment by wtbarnes** [comment]
Ah I see. Yes I didn't think about that.  I'll do a quick PR to fix this.

**Pull request merged**
