### PR TITLE
add a voigt filter

### PR DESCRIPTION
**Pull request by kdere**
modified the Lorentzian
really a pseudo-voigt filter
got for analysis of x-ray crystal spectra

### CODE REVIEW

**Comment by kdere** [comment]
I think I understand the problem with ioneq but I don't know why it is acceptable in 3.4 and not 2.7
closing up shop for today

**Comment by wtbarnes** [comment]
What was the ioneq problem?

**Comment by kdere** [comment]
a lot of things were getting divided by zero.  put in some checks and some try/except statement.
next will have to clean up the comment out print statements

**Comment by wtbarnes** [comment]
Ok I see. As a suggestion, I think we should avoid merging code into master that still has the "debugging marks" left in it (e.g. commented out code, print statements, etc).

**Comment by kdere** [comment]
I agree but I was not exactly sure it would actually get by Travis and I would have to revisit it.

**Comment by wtbarnes** [comment]
Travis will run all of the tests each time you push a commit to the branch you created the PR from. So you can know whether it's passing before you merge.

**Comment by kdere** [comment]
should have thought of that

**Pull request merged**
