### PR TITLE
new use of mathjax + other updates to documentation

### PR DESCRIPTION
**Pull request by kdere**
last merge request failed because of constants.py and index.rst but I have updated them

### CODE REVIEW

**Comment by wtbarnes** [comment]
Why was the changelog entry removed from the toctree in `docs/source/index.rst`?

**Comment by kdere** [comment]
now that I think about it, it was included inside an RVS error listing.  So I replaced it and created a pull request and that was accomplished OK but the 'changelog' is still not in index.rst.  I don't understand what is happening.  Perhaps it you were to try it?

**Comment by wtbarnes** [comment]
Looks like #34 solved it. Docs are building now too.

**Comment by ehsteve** [comment]
👍 for always up to date online docs!

**Pull request merged**
