### PR TITLE
tag/version-0.6.0

### PR DESCRIPTION
**Pull request by kdere**
created a tag dir with the version-0.6.0 inside

### CODE REVIEW

**Comment by ehsteve** [comment]
@kdere is the idea to create a new tag dir for every version? This would mean that this repo would include every version of chiantipy at once? Is that would you are trying to accomplish? There is a way to add virtual tags to a particular point in the history to tag a release. This is the standard way of handling it in git. You can see the sunpy implementation of this here https://github.com/sunpy/sunpy/releases.

**Comment by ehsteve** [comment]
Also what is the difference between what is in the ls directory and what is in the chianti directory?

**Comment by kdere** [comment]
not sure how the ls directory got there.  I will look into it and probably remove it

**Comment by kdere** [comment]
I am not sure how the 'ls' directory got there.  will look into it and probably delete it

**Comment by ehsteve** [comment]
I would suggest that you revert this change and fix it and resubmit this PR as these are fairly large changes and include lots of duplicate files.

**Comment by ehsteve** [comment]
To be clear, a git repository remembers everything (you cant really delete files) so if you have multiple copies of files it carries both copies in its history. This will not be an issue for users but will unneccesarily bloat the repository for developers.

**Comment by ehsteve** [comment]
@kdere Would you like to some help getting things started here? It's fairly easy if you are familiar with the process and does not need to be repeated so doesn't necessarily make sense for multiple people to learn how to do it. Let me know.

**Comment by kdere** [comment]
Hi Steve, I think it would be a good idea for you to restart this thing.  I am not particularly familiar with git and it sounds like you could do it more easily than I.

**Pull request merged**
