### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by wtbarnes**
# ~~NOT READY TO BE MERGED!~~ READY TO MERGE!
## Creating this PR to show progress on documentation updates.

This PR aims to update nearly all of the docstrings to be compatible with the [Astropy docstring rules](http://docs.astropy.org/en/stable/development/docrules.html#class-docstrings). It also includes some changes to the README and main parts of the documentation. 

If you'd like to do some work on any of the docstrings in ChiantiPy or any parts of the Sphinx documentation, **leave a comment on this PR** so that we can try to avoid any conflicts.

### CODE REVIEW

**Comment by kdere** [comment]
Just to be clear, I will not merge this pull request.

The firs thing I need to do is some edits on _IonTrails to convert the integer divides to be P3 compatible.

After that, I want to look at the QuickStart notebook and sphinx documents.

**Comment by wtbarnes** [comment]
Sounds good. I just wanted to make it clear what updates I am working on at the moment. I will try to confine this PR to mostly docstring edits. These are pretty straightforward and mostly a matter of formatting since in most cases, all the info about the function is already there.

**Comment by kdere** [comment]
I finished the code edits to _IonTrails.py but started working on the doc strings.  As I went along, it became clear that I should document the Ion.py class first.  So I will work on that next unless I hear from you.  
Also, it is clear that some sort of guide/manual, with equations, is necessary.  Probably have to do this in latex or libre office.

**Comment by wtbarnes** [comment]
Ok sounds good. For the sake of making this PR a reasonable length, I'll try to confine my changes to minor fixes in `docs/source` and docstrings in `ChiantiPy/tools` and not touch anything in `ChiantiPy/core`. Better to break up changes into multiple PRs.  

[Here's a very helpful reference for writing Astropy/NumPy compliant docstrings](http://docs.astropy.org/en/stable/development/docrules.html). The more general [Astropy doc guidelines](http://docs.astropy.org/en/stable/development/docguide.html) are also very helpful. 

Regarding a guide/manual, Sphinx actually provides a lot of nice ways for doing this without having to stray from the documentation. You can easily [typeset equations via LaTeX in RST](http://www.sphinx-doc.org/en/stable/ext/math.html) and the extensions provided by Astropy allow for easy references ([see this example that I've implemented in the ChiantiPy docs](http://www.sphinx-doc.org/en/stable/ext/math.html)). This is a pretty big topic itself so I would suggest moving this discussion to its own issue.

**Comment by kdere** [comment]
is this ready to be merged?

**Comment by wtbarnes** [comment]
Not quite yet. Almost there though.

A few more docstring updates in `tools/util.py` and I've made some changes to the `README.rst` as well that I think make the quick setup/install instructions a bit more clear. I'll try to finalize these changes by this evening/tomorrow morning and post back here once they are ready to be merged.

It's not quite ready yet, but once my edits to the `README.rst` are finished you can preview them on my fork of ChiantiPy on the `doc_updates` branch. Let me know what you think works/doesn't work or if you'd rather just have it back to the original form.

**Comment by wtbarnes** [comment]
Ok I've wrapped up all of the docstring fixes/formatting in `ChiantiPy/tools`. 

The other big change I made was a rewrite of the README that you see when you go to the GitHub page. You can [preview it here](https://github.com/wtbarnes/ChiantiPy/tree/doc_updates) on my fork. It is a lot more terse, but I think it is a bit more readable and will help people get up and going with ChiantiPy more quickly. I've made sure to link to the main Chianti webpage as well as the ChiantiPy docs. It's also now a markdown file rather than a restructured text file since GitHub tends to play nicer with these.

I've moved the version history that was at the top of the README to a "Changelog" page in the docs. 

With these changes, the docs appear to be building just fine so this is ready to merge on my end. If you have any comments or want to see any changes/corrections, let me know!

**Comment by kdere** [comment]
merge performed.
README.md looks much better and changelist is a better way to handle that stuff

**Pull request merged**
