### PR TITLE
_setup -> setup and a number of doc changes

### PR DESCRIPTION
**Pull request by kdere**

### CODE REVIEW

**Comment by kdere** [comment]
the kind of errors i am getting at travis is with dependencies
- numpy 1.12* -> python2.7
- Python3.6*
I have numpy 1.12 installed on my machine 
I have Python 2.7 and Python 3.4.5 installed
if I do
> conda info numpy
numpy 1.12 seems to require either Python 3.5 or Python 3.6

**Comment by wtbarnes** [comment]
Yeah this is a bit strange...Numpy v1.12 seems to be the problem for 2.7, 3.4, and 3.5 but it seems to manifest in different ways...

I'll ask around to try and figure out what might be the problem, but for now I think we can just force v1.11 of NumPy on Travis. Just add,

```yaml
- NUMPY_VERSION='1.11'
```

right after the `PYQT_VERSION` line under the `global` heading in the `.travis.yml` file.

**Comment by wtbarnes** [comment]
See [this issue](https://github.com/astropy/ci-helpers/issues/166) on the `astropy/ci-helpers` page. It seems to be an issue with versions in the ci-helpers not being quite up to date with the latest stable NumPy release (v1.12). I suspect this will be fixed soon, but for now I would suggest just pinning NumPy to v1.11

**Comment by kdere** [comment]
We should be able to pin things to numpy 1.11.  Can you do that?
I would then like to make a release soon after.

**Comment by wtbarnes** [comment]
Yes no problem. Just go ahead and merge this failing PR and then I'll open a new one to fix this.

**Comment by kdere** [comment]
OK, merged the pull request #93

**Pull request merged**
