### PR TITLE
 added notice if no ions have been selected

### PR DESCRIPTION
**Pull request by kdere**
this is in _specTrails.ionGate

### CODE REVIEW

**Comment by wtbarnes** [comment]
I suspect this is just a network problem on the Travis CI end and has nothing to do with the ChiantiPy codebase or the changes you made.  All of the other versions (2.7 and 3.4) didn't have a problem here so I don't think this is a big problem.

I would try just restarting the build by hitting the "Restart Build" button at the top of the page.

**Comment by wtbarnes** [comment]
I think wherever the the CHIANTI database is hosted must have been down for a bit because the RTD build failed as well at the same spot. However, I've just tested the curl/tar command on my Linux machine and everything seems to be working fine now. I would just restart the build on Travis and RTD. I think both should work fine now.

**Comment by kdere** [comment]
I restarted the build on Travis and that worked and showed up on the github page.  I also started the build on RTD and that passed but so far has not shown up on the github page.
Our server for the database is a shared server and can be slow.

**Comment by wtbarnes** [comment]
Ok great. Yeah I'm not sure why the RTD badge is showing up red. Sometimes the service used to display the badge colors takes a long time to catch up.

**Pull request merged**
