### PR TITLE
Fixing Read the Docs build

### PR DESCRIPTION
**Pull request by wtbarnes**
RTD build broken again. Some things got messed up after the "big merge" in PR #21. Everything fixed now.

### CODE REVIEW

**Comment by kdere** [comment]
rtd fix merged

**Comment by wtbarnes** [comment]
Thanks for merging this. The docs are still failing for some reason. I had this problem when testing on my fork. In the end, I had to clean out the RTD build (on [my fork](https://readthedocs.org/projects/wtb-chiantipy/))in order to fix it.

@kdere I think you will have to do this since you have the correct permissions. 
1. On the [Read the Docs ChiantiPy dashboard](http://readthedocs.org/projects/chiantipy/), click the "Versions" button and in the "latest" pane, hit "Wipe"
2. Go to the "Builds" tab and hit "Build Version". This restarts the docs build process.

Hopefully this fixes it.

**Comment by kdere** [comment]
just did that.  looks like it has started.

**Comment by wtbarnes** [comment]
Great. Looks like everything is building correctly now.

**Comment by kdere** [comment]
great!
one thing I noticed in Manifest.in was that it looked for a file 'VERSION' which we don't have.  It would be good to be able to use ChiantiPy and find out what version it was.  I did this before but I was told I did not do it like most people expected.  However, this is not a burning issue

**Comment by Cadair** [comment]
SunPy uses some code from the astropy package template to do that, including encoding the git hash for non-release versions, which makes it very nice for debugging user reported issues.

**Comment by wtbarnes** [comment]
I think I merged the old `MANIFEST.in` with the version in astropy_helpers so there are probably some issues to be worked out before a new package can be built for PyPI.

**Pull request merged**
